// src/app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/components/providers'; // Ensure this includes QueryClientProvider
import CartProvider from '@/components/CartProvider';
// import { CartProvider } from 'use-shopping-cart';
import { WishlistProvider } from '@/context/WishlistContext';
import { loadStripe } from '@stripe/stripe-js';
import { Elements } from '@stripe/react-stripe-js';
const stripePromise = loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY!);
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartProvider>
      <html lang="en">
        <body className={inter.className}>
        <WishlistProvider>
          <Providers>
            {children}
          </Providers>
           </WishlistProvider>
        </body>
      </html>
    </CartProvider>
  );
}